In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
print('x = ', x)

x =  [1 2 3 4 5]


In [4]:
print('x has dimensions:', x.shape)

x has dimensions: (5,)


In [5]:
print('x is an object of type:', type(x))

x is an object of type: <class 'numpy.ndarray'>


In [6]:
print('The elements in x are of type:', x.dtype)

The elements in x are of type: int64


In [7]:
x = np.array(['Hello', 'World'])

In [9]:
print('x = ', x)

x =  ['Hello' 'World']


In [10]:
print('x has dimensions:', x.shape)

x has dimensions: (2,)


In [11]:
print('x is an object of type:', type(x))

x is an object of type: <class 'numpy.ndarray'>


In [12]:
print('The elements in x are of type:', x.dtype)

The elements in x are of type: <U5


In [13]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [14]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [15]:
# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [17]:
#upcasting
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

In [18]:
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [19]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


In [20]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)


In [21]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


In [24]:
arr = np.arange(36).reshape(3, 4, 3)
#https://realpython.com/numpy-array-programming/

In [23]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])